apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app 
spec:
  selector:
    matchLabels:
      app: argocd-app
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
      - name: argocd-app-container
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 9000